server:
  port: 8087
logging:
  level:
    root: DEBUG
    javax.management: ERROR
    org.springframework.security.web.FilterChainProxy: DEBUG
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: wms-service
            uri: http://localhost:9001
            predicates:
              - Path=/** # Path predicate for URI path matching
            filters:
              - PrefixPath=/api
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: j-service-client
          client-secret: j-service-client
          introspection-uri: ${WMS_SERVICE_SSO_URL:http://localhost:7777}/oauth2/token-info
