import { createApp } from 'vue';
import App from './App.vue';
import router  from './router';
import vuetify from './plugins/vuetify';
import '@/scss/style.scss';
import PerfectScrollbar from 'vue3-perfect-scrollbar';
import VueApexCharts from 'vue3-apexcharts';
import VueTablerIcons from 'vue-tabler-icons';
import Maska from 'maska';
import setupInterceptors from '@/services/setupInterceptors';
import { store } from '@/store';
const app = createApp(App);
setupInterceptors();
app.use(router);
app.use(PerfectScrollbar);
app.use(VueTablerIcons);
app.use(store);
app.use(Maska);
app.use(VueApexCharts);
app.use(vuetify).mount('#app');
